spring:
  application:
    name: spring-kafka-elk-toy
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-kafka-elk-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    root: INFO
